version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - "./.env"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - "./.env"
    ports:
      - "82:80"
    restart: always
#  app:
#    env_file:
#      - "./.env"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    build:
#      context: ./
#      target: dev
#    volumes:
#      - .:/src
#      - /src/node_modules
#    command: "npm run start:dev"
#    ports:
#      - "8080:8080"
#    environment:
#      - PORT=${PORT}
#      - DATABASE_URL=${DATABASE_URL}
#      - JWT_SECRET=${JWT_SECRET}
